server:
  port: 8081
spring:
  application:
    name: community-group-buy
  datasource:
    jdbc: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/dianping?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  redis:
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASSWORD:}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:10}
    lettuce:
      pool:
        max-active: ${REDIS_POOL_MAX_ACTIVE:10}
        max-idle: ${REDIS_POOL_MAX_IDLE:10}
        min-idle: ${REDIS_POOL_MIN_IDLE:1}
        time-between-eviction-runs: 10s
#    cluster:
#      nodes:
#        - ${REDIS_CLUSTER_NODE_1:127.0.0.1:7001}
#        - ${REDIS_CLUSTER_NODE_2:127.0.0.1:7002}
#        - ${REDIS_CLUSTER_NODE_3:127.0.0.1:7003}
#        - ${REDIS_CLUSTER_NODE_4:127.0.0.1:8001}
#        - ${REDIS_CLUSTER_NODE_5:127.0.0.1:8002}
#        - ${REDIS_CLUSTER_NODE_6:127.0.0.1:8003}
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.231.244:27001
#        - 192.168.231.244:27002
#        - 192.168.231.244:27003

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.buyTogether.entity # 别名扫描包
logging:
  level:
    com.buyTogether: debug
sa-token:
  token-name: satoken
  timeout: ${SA_TOKEN_TIMEOUT:1296000}
  active-timeout: ${SA_TOKEN_ACTIVE_TIMEOUT:-1}
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
